### ISSUE TITLE
Enterprise Dashboard for ESG standard

### ISSUE THREAD

**Issue by sov3333** [web3devcommunity/lantana-hacksg#18]
Part of  #Impact & Donations & Traceability Dashboard 

As a enterprise user, I am able to track

- all initiatives I partiicpate in funding, and the related impact certificate
- see the total donations and my part of it

I can make use of the impact dashboard and export as sustainability standard format

I will see suggested category 

![Image](https://user-images.githubusercontent.com/1883877/237684754-dff03f54-a9ed-4903-ba07-3cd0db6eb8f6.png)

https://github.com/orgs/web3devcommunity/projects/1/views/4?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C42947347%2C42962471%2C42973989%5D&pane=issue&itemId=27912874

https://skbi.smu.edu.sg/sites/skbi.smu.edu.sg/files/2022-02/Impact%20Measurement%20and%20Standards%20White%20Paper.pdf

**Comment by sov3333** [comment]
created a skeleton page for the enterprise dashboard as per figma via https://github.com/web3devcommunity/lantana-hacksg/pull/17/commits/0059ff727ef9bbc211d6a7dc718aa3030eacaf72, but i think we will still need to add:
- a list of all initiatives the enterprise participated in, and the related impact certificate
- see the total donations and my part of it

![Image](https://github.com/web3devcommunity/lantana-hacksg/assets/8282076/1449b0b8-f414-4ea3-ab1f-c1b24578d58f)

**Comment by sov3333** [comment]
![image](https://github.com/web3devcommunity/lantana-hacksg/assets/8282076/4df9166a-7ada-453f-a381-d4043255c68e)
via https://github.com/web3devcommunity/lantana-hacksg/pull/17/commits/d58f9605ff18d7d057678fadd71d45bce94cbe37

**Comment by debuggingfuture** [comment]
![beach_clean_up_hypercert](https://github.com/web3devcommunity/lantana-hacksg/assets/1883877/592563b0-421b-422a-b02c-733861ada732)
